export const FETCHED_PLAYERS = 'FETCHED_PLAYERS';
export const FETCHED_PLAYERS_NEXT_PAGE = 'FETCHED_PLAYERS_NEXT_PAGE';
export const FETCHING_PLAYER_DETAILS = 'FETCHING_PLAYER_DETAILS';
export const FETCHED_PLAYER_DETAILS = 'FETCHED_PLAYER_DETAILS';
export const FETCHED_PLAYER_STATS = 'FETCHED_PLAYER_STATS';
export const FETCHED_PLAYER_PICTURE = 'FETCHED_PLAYER_PICTURE';

export const SET_REQUEST_PARAMS = 'SET_REQUEST_PARAMS';
export const SET_RESPONSE_METADATA = 'SET_RESPONSE_METADATA';
